version: "3.3"
services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        restart: unless-stopped
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - event-driven-mono
    jaeger:
        image: jaegertracing/all-in-one
        container_name: jaeger
        restart: unless-stopped
        networks:
            - event-driven-mono
        ports:
            - 5775:5775/udp
            - 5778:5778
            - 6831:6831/udp
            - 6832:6832/udp
            - 9411:9411
            - 14268:14268
            - 16686:16686
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 27017:27017
        networks:
            - event-driven-mono
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
            ME_CONFIG_BASICAUTH: false
        networks:
            - event-driven-mono

networks:
    event-driven-mono:
        driver: bridge
